### ISSUE TITLE
Player crash after 4 hour and 13 minutes

### ISSUE THREAD

**Issue by KurtKomell** [tooll3/t3#277] opened 2023-07-31 20:23 UTC
Hi,
Player crash because of out of memory excemption.

Logfile show this:
04:13:45.520 (Error): Updating Shader Resource View failed: HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.

04:13:45.546 (Error): Updating Shader Resource View failed: HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Für diesen Vorgang sind nicht genügend Speicherressourcen verfügbar.
[2023_07_31-23_31_44_692.log](https://github.com/tooll3/t3/files/12221814/2023_07_31-23_31_44_692.log)

What can i do?

Thank You for your Support.

**Comment by pixtur** [comment] 2023-08-09 20:33
Hi @KurtKomell . I'm sorry to hear that. Can you provide more details so I can narrow down the potential problem? Were you using video-playback by any chance?

**Comment by KurtKomell** [comment] 2023-08-09 20:53
I use the ndi Input and spout Input to in different PCs. I can send you the exportfolder for the Player.exe.

**Comment by pixtur** [comment] 2023-08-11 09:18
Oh. I can see that. The NDI-Plugin we're using seems to have some memory and resource-leaks.
Which resolution did you use for the transferred image?

**Comment by KurtKomell** [comment] 2023-08-18 18:44
Hi i use 1080p or 720p in both situation the player stop after 4 or 5 hours. It doesnt matter to be spout or ndi in. I think it is a problem of the Nvida rtx. I cannt Test it on a intel system. I do this later. Now i have a  inquirey to show my installation from  7 am till 6 pm. So i would be nice to here from you with a solution. I can load my export folder up and send to you. Maybe i try to reboot the system all 4 hours, thats not the best way but a workaround. Thank you very much.

**Comment by pixtur** [comment] 2023-08-23 21:54
Hi Kurt. A link to the export-folder would be very useful. You can send me a private DM on discord or post it here.

**Comment by KurtKomell** [comment] 2023-09-06 18:17
Hi Pixtur,
here the link zum Folder.
please answer me wehn you get it then i can delete it.
https://1drv.ms/u/s!AmxCgNCjTM1PhfdpGjEu-PHSLpKYWg?e=9UILP3

**Comment by pixtur** [comment] 2023-09-10 11:03
After some experimentation, I could reproduce a similar problem wit the player: For me the timing was;
![image](https://github.com/tooll3/t3/assets/1732545/3f60bb6b-0012-4079-b202-4316f76ac6dd)

It's quite interesting that you had a out of memory exception just before the crash.
But it's quite strange that the suspent-times are sooo close together.

I will try to investigate further.

**Comment by pixtur** [comment] 2023-09-10 11:08
Some [sites](https://support.lumion.com/hc/en-us/articles/360008130654-How-do-you-resolve-a-GPU-device-instance-has-been-suspended-error-) recommended to increase TdrDelay but I don't believe that this is related to the current issue.

https://learn.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys

**Comment by pixtur** [comment] 2023-09-10 15:20
It looks like the freeze is occurring after 1024^2 frames which probably means there is a resource leak, e.g. in the handling of SRVs (the tier 2 limit for them being 1M). I will try to investigate further.

**Comment by pixtur** [comment] 2023-12-29 19:12
It took some time to narrow this down but now it should be fixed in the next version.

**Closed by pixtur** 2023-12-29 19:12 UTC
